// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnBowwENstI1HVqB8JjuDjPtKaNyN9cWA',
    appId: '1:19411767388:android:d3f0266b6ea91d08391699',
    messagingSenderId: '19411767388',
    projectId: 'sleepless-6bce2',
    storageBucket: 'sleepless-6bce2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiAfOQ1awOYCHD-4yJ4v9KrOyhDGErXHk',
    appId: '1:19411767388:ios:f3c2574fbd3b8fcc391699',
    messagingSenderId: '19411767388',
    projectId: 'sleepless-6bce2',
    storageBucket: 'sleepless-6bce2.firebasestorage.app',
    iosBundleId: 'net.coventry.sleepless',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWobLFywVNlm6-HkVrxbpA3TJXwNNwN_8',
    appId: '1:19411767388:web:2647fd9b53850017391699',
    messagingSenderId: '19411767388',
    projectId: 'sleepless-6bce2',
    authDomain: 'sleepless-6bce2.firebaseapp.com',
    storageBucket: 'sleepless-6bce2.firebasestorage.app',
    measurementId: 'G-69J1PVTHSW',
  );

}